import type { Translations } from './types';
import { en } from './en';

export const ar: Translations = {
  ...en,
  baseCurrency: { ...en.baseCurrency, TWD: 'دولار تايواني', USD: 'دولار أمريكي', JPY: 'ين ياباني', EUR: 'يورو', GBP: 'جنيه إسترليني', HKD: 'دولار هونغ كونغ', KRW: 'وون كوري', CAD: 'دولار كندي', INR: 'روبية هندية', CNY: 'يوان صيني', AUD: 'دولار أسترالي', SAR: 'ريال سعودي', BRL: 'ريال برازيلي' },
  common: { ...en.common, confirm: 'تأكيد', cancel: 'إلغاء', delete: 'حذف', edit: 'تعديل', save: 'حفظ', close: 'إغلاق', loading: 'جاري التحميل...', search: 'بحث', logoutConfirm: 'تسجيل الخروج؟', baseCurrency: 'العملة الأساسية', upgrade: 'ترقية', footerLocalDataPrivacy: 'تُخزَّن جميع بيانات المعاملات محلياً على جهازك لحماية خصوصيتك.' },
  nav: { dashboard: 'لوحة التحكم', history: 'السجل', funds: 'الأموال', accounts: 'الحسابات', rebalance: 'إعادة التوازن', simulator: 'المحاكي', splits: 'تقسيم الأسهم', help: 'النظام', logout: 'تسجيل الخروج' },
  pages: { ...en.pages, dashboard: 'لوحة المحفظة', history: 'السجل (المعاملات والتدفق)', funds: 'إدارة الأموال', accounts: 'إدارة الحسابات', rebalance: 'إعادة التوازن', simulator: 'محاكي التخصيص', splits: 'إدارة تقسيم الأسهم', help: 'النظام والنسخ' },
  login: { title: 'تسجيل الدخول TradeView', subtitle: 'مدير الأصول الاستثمارية', email: 'البريد', password: 'كلمة المرور', login: 'دخول', privacy: 'الخصوصية', privacyDesc: 'البيانات مخزنة محلياً. لا جمع للبيانات الشخصية.', riskDisclaimer: 'إخلاء المسؤولية', riskDisclaimerDesc: 'الاستثمار ينطوي على مخاطر.' },
  dashboard: { 
    ...en.dashboard, 
    netCost: 'صافي الاستثمار', 
    totalAssets: 'إجمالي الأصول', 
    totalPL: 'الربح/الخسارة', 
    annualizedReturn: 'العائد السنوي (XIRR)',
    detail: 'التفاصيل',
    includeCash: 'بما في ذلك النقد',
    detailedStatistics: 'إحصائيات مفصلة',
    totalCost: 'إجمالي التكلفة',
    totalPLAmount: 'إجمالي مبلغ الربح/الخسارة',
    accumulatedCashDividends: 'الأرباح النقدية المتراكمة',
    accumulatedStockDividends: 'أرباح الأسهم المتراكمة',
    yearDividendTaxTitle: 'الاستقطاعات المتعلقة بالتوزيعات هذا العام (مرجع)',
    yearWithheldNhi: 'إجمالي قسط NHI الإضافي (للسجلات المُدخلة فقط)',
    yearUsWithholding: 'إجمالي ضريبة الحجب الأمريكية (السجلات المُدخلة؛ وإذا كانت فارغة يُقدَّر 30% من الصافي)',
    yearUsWithholdingHint: 'تعبئة "ضريبة الحجب" في سجل التوزيع النقدي يجعل الإحصاء أدق.',
    annualizedReturnRate: 'معدل العائد السنوي',
    avgExchangeRate: 'متوسط سعر الصرف (TWD/USD)',
    currentExchangeRate: 'سعر الصرف الحالي',
    totalReturnRate: 'معدل العائد الإجمالي',
    assetVsCostTrend: 'اتجاه الأصول مقابل التكلفة',
    assetTrendMergedSubtitle:
      'الأعمدة الرئيسية يساراً: تكلفة الاستثمار المتراكمة والربح/الخسارة؛ الخطان الأزرق/البرتقالي: إجمالي الأصول والتقدير؛ الأعمدة الرفيعة يميناً: التدفق الداخل والخارج وربح/خسارة السوق والدخل السنوي.',
    toggleYearlyFlowBars: 'أعمدة التدفق السنوي',
    yearlyFlowIn: 'تدفق سنوي داخل',
    yearlyFlowOut: 'تدفق سنوي خارج',
    yearlyMarketPL: 'ربح/خسارة السوق السنوي',
    yearlyIncome: 'توزيعات/فوائد سنوية',
    aiCorrectHistory: 'تصحيح الأصول التاريخية بالذكاء الاصطناعي',
    marketDistribution: 'وزن الرمز',
    allocation: 'التخصيص',
    allocationDonutSubtitle:
      'الحلقة الخارجية: كل أصل (مثل VT) كنسبة من المراكز / الحلقة الداخلية: أسهم/سندات (باستثناء النقد)',
    stockBondRatioBadge: 'أسهم / سندات',
    legendMarketOuter: 'المراكز حسب الرمز (خارجي)',
    legendStockBondInner: 'أسهم/سندات (داخلي)',
    assetClassOverrideTitle: 'تصنيف مخصص للأسهم/السندات (تجاوزات)',
    tickerSymbolLabel: 'الرمز',
    tickerPlaceholderExamples: 'مثال: AGG / TLT / BND',
    assetClassSelectLabel: 'الفئة',
    equityLabelShort: 'أسهم',
    bondLabelShort: 'سندات',
    saveAssetClassOverride: 'حفظ التجاوز',
    clearTickerOverride: 'مسح',
    currentOverridesHeading: 'التجاوزات الحالية',
    removeOverrideTitle: 'انقر للإزالة',
    annualPerformance: 'الأداء السنوي',
    year: 'السنة',
    startAssets: 'الأصول الأولية',
    annualNetInflow: 'صافي التدفق السنوي',
    endAssets: 'الأصول النهائية',
    annualProfit: 'الربح السنوي',
    annualROI: 'العائد على الاستثمار السنوي',
    brokerageAccounts: 'قائمة الحسابات',
    accountName: 'اسم الحساب',
    totalAssetsNT: 'إجمالي الأصول',
    marketValueNT: 'القيمة السوقية',
    balanceNT: 'الرصيد / الدين',
    balanceColumnTooltip:
      'الوساطة: رصيد نقدي؛ الخصوم: أصل الدين.',
    profitNT: 'الربح',
    profitFormulaTooltip: 'إجمالي الربح/الخسارة = غير محقق + محقق + توزيعات/فوائد. الربح المحقق يحتسب من SELL فقط، والتحويلات مستبعدة.',
    accountReturnRateTooltip:
      'العائد التراكمي = P/L ÷ المقام. صافي الإيداع؛ إن ≤ 0 التكلفة المتراكمة. تحويل بقيمة السوق: تحقيق في المصدر، تكلفة السوق في الوجهة. بلا مراكز = مغلق.',
    accountClosedBadge: 'مغلق',
    unrealizedPL: 'ربح/خسارة غير محققة',
    realizedPL: 'ربح/خسارة محققة',
    dividendInterest: 'توزيعات/فوائد',
    displayCurrency: 'عملة العرض', 
    ntd: 'دولار تايواني', 
    usd: 'دولار أمريكي',
    portfolioHoldings: 'المراكز',
    mergedDisplay: 'مدمج (حسب الرمز)',
    detailedDisplay: 'مفصل (حسب الحساب)',
    aiUpdatePrices: 'تحديث الأسعار وسعر الصرف (AI)',
    estimatedGrowth8: 'نمو متوقع 8%',
    annualizedReturnTarget8: 'هدف 8٪',
    chartLoading: 'جاري تحميل الرسم البياني...',
    noChartData: 'يرجى إضافة الإيداعات والمعاملات أولاً',
    noHoldings: 'لا توجد مراكز',
    noAccounts: 'لا توجد حسابات وسيطة. يرجى إضافة حسابات في الحسابات.',
    costBreakdown: 'تفصيل تكلفة الاستثمار الصافي',
    netInvestedBreakdown: 'تفصيل الاستثمار الصافي',
    calculationFormula: 'الصيغة: الاستثمار الصافي = الإيداعات - السحوبات',
    formulaNote: 'ملاحظة: للحسابات بالدولار الأمريكي، يتم استخدام سعر الصرف التاريخي إن أمكن، وإلا فسيتم استخدام السعر الحالي من الإعدادات. التحويلات والفوائد غير مدرجة في التكلفة.',
    attention: 'انتباه',
    date: 'التاريخ',
    category: 'الفئة',
    originalAmount: 'المبلغ الأصلي',
    twdCost: 'التكلفة ({currency})',
    totalNetInvested: 'الإجمالي (الاستثمار الصافي)',
    deposit: 'إيداع(+)', 
    withdraw: 'سحب(-)',
    fixedTWD: 'مبلغ TWD ثابت',
    historicalRate: 'السعر التاريخي',
    currentRate: 'السعر الحالي',
    taiwanDollar: 'الدولار التايواني',
    twdIncludesFee: 'TWD (يشمل الرسوم)',
    chartLabels: {
      investmentCost: 'تكلفة الاستثمار',
      accumulatedPL: 'الربح/الخسارة المتراكم',
      estimatedAssets: 'إجمالي الأصول المتوقع (8%)',
      totalAssets: 'إجمالي الأصول',
      toDate: ' حتى الآن',
      realData: ' (السعر الحقيقي)',
      estimated: ' (متوقع)',
      profit: 'ربح',
      loss: 'خسارة',
      barName: 'الربح/الخسارة المتراكم: أخضر=ربح أحمر=خسارة',
      yearlyPeriodRoi: 'العائد السنوي',
      chartLegendYearlyPeriodRoi:
        'خط وردي (يمين %): نقطة واحدة لكل سنة عند الربع الرابع (السنة الحالية: «حتى اليوم» إن لم يوجد الربع الرابع).',
    },
    noHoldingsData: 'لا توجد بيانات عن الحيازات',
    realHistoricalData: 'بيانات تاريخية حقيقية',
    formulaLabel: 'الصيغة: ',
    aiCorrectHistoryTitle: 'تحرير يدوي أو استخدام AI لتصحيح الأسعار التاريخية',
    aiAdvisor: 'مستشار Gemini AI', 
    aiAdvisorDesc: 'تحليل تخصيص محفظتك والمخاطر والفرص المحتملة.',
    startAnalysis: 'بدء التحليل',
    analyzing: 'جاري التحليل...',
    viewCalculationDetails: 'عرض التفاصيل',
    riskWarning: 'تحذير مخاطر الاستثمار',
    riskWarningDesc: 'الاستثمار ينطوي على مخاطر. الأداء السابق لا يضمن النتائج المستقبلية.',
    chartLegendQuarterSnapshot: '✅ لقطة نهاية الربع (بيانات Yahoo)',
    chartLegendLinearInterpolation:
      '⚠️ استيفاء خطي — افتح الأسعار التاريخية لجلب البيانات الناقصة',
    netWorth: 'صافي الثروة',
    totalDebt: 'إجمالي الدين',
    leverageNetInvestedNote: 'صافي الاستثمار قد يشمل سحوبات القرض (~{amount})',
    leverageXirrWarning: 'XIRR يشمل أموالاً مقترضة — فسّر بحذر',
    debtDisbursement: 'سحب قرض',
    debtRepayment: 'سداد قرض',
    leverageFormulaNote: 'سحب/سداد القرض (خصوم↔وساطة) يدخل صافي الاستثمار وXIRR. فائدة القرض لا.',
    debtAccountsTitle: 'الائتمان والدين',
    creditUsedOfLimit: 'مستخدم {used} / حد {limit} (استخدام {percent}%)',
    estimatedMonthlyInterest: 'فائدة الشهر القادم المقدرة',
    estimatedMonthlyInterestNote: 'تقدير من الرصيد الحالي والمعدل السنوي (شهر واحد)',
    notInvestmentAdvice: 'ليس نصيحة استثمارية.' 
  },
  marketChart: {
    title: 'أداء الأسواق',
    subtitle: 'العائد التراكمي والوزن حسب السوق',
    cumulativeReturn: 'العائد التراكمي',
    weight: 'الوزن',
    value: 'القيمة',
    cumulativeReturnShort: 'العائد',
    weightShort: 'الوزن',
    valueShort: 'القيمة',
    noData: 'لا توجد بيانات',
    ratio: 'النسبة',
  },
  waterfall: {
    title: 'مخطط شلال التدفق النقدي',
    subtitle: 'صافي القيمة المتراكم: الإيداعات، الأرباح/الخسائر، الأرباح الموزعة، السحوبات',
    byYear: 'سنوي',
    byQuarter: 'ربع سنوي',
    deposit: 'إيداع',
    withdraw: 'سحب',
    stockPL: 'أرباح/خسائر الأسهم',
    dividend: 'توزيعات الأرباح',
    net: 'صافي الفترة',
    runningTotal: 'متراكم',
    periodNet: 'صافي',
    noData: 'لا توجد بيانات تدفق نقدي',
    plPositive: 'أرباح/خسائر (+)',
    plNegative: 'أرباح/خسائر (−)',
    legendHintStart: 'إجمالي قيمة المحفظة (بما فيها النقد) في بداية كل فترة.',
    legendHintInflow: 'الإيداعات ناقص السحوبات خلال الفترة. أزرق = صافي تدفق داخل، برتقالي = صافي خروج.',
    legendHintDividend: 'أرباح نقدية وفوائد تُسجَّل في الفترة.',
    legendHintPL: 'تغيّر الأصول بعد صافي التدفق والدخل؛ تقريباً ربح/خسارة السوق. أخضر = ربح، أحمر = خسارة.',
    includingLabel: '(بما في ذلك {item})',
  },
  dividendHeatmap: {
    title: 'خريطة حرارة الأرباح',
    subtitle: 'كل خلية = أرباح شهرية. أغمق = أعلى.',
    totalDividend: 'إجمالي الأرباح',
    noData: 'لا توجد سجلات أرباح نقدية',
    bestMonth: 'أفضل شهر',
    less: 'أقل',
    more: 'أكثر',
    monthlyBreakdown: 'التفاصيل الشهرية',
    yearTotal: 'السنة',
    monthTotal: 'الشهر',
    recordedLabel: 'مسجل',
    pendingLabel: 'معلق',
  },
  dividendTax: {
    twTooltipTitle: 'تقدير ضريبي (مرجع)',
    estSinglePayout: 'توزيع متوقع لدفعة واحدة (آخر توزيع للسهم × الكمية المحتفظ بها)',
    estNhiFee: 'تقدير قسط NHI الإضافي (2.11%، تقديري)',
    splitHint0050: 'إذا كان الصرف عبر وسطاء/جهات دفع متعددة فقد يختلف تجاوز الحد؛ التطبيق الفعلي حسب جهة الصرف.',
    usNetTooltipTitle: 'حجب توزيعات الأسهم الأمريكية (مرجع)',
    estGrossPerPayout: 'إجمالي متوقع لكل دفعة (توزيع السهم × عدد الأسهم)',
    estNetAfterWithholding: 'صافي متوقع بعد الضريبة (على فرض حجب 30%، أي نحو 70%)',
    upcomingTitle: 'توزيعات متوقعة خلال 90 يوماً (Yahoo)',
    upcomingSubtitle: 'المبلغ تقديري بناءً على "آخر توزيع نقدي للسهم × الكمية الحالية"، وقد يختلف عن الفعلي.',
    upcomingEmpty: 'لا توجد حالياً مواعيد استحقاق مطابقة، أو لا تتوفر بيانات عامة كافية.',
    upcomingExDate: 'تاريخ الاستحقاق',
    upcomingInferredMonthHint:
      'هذا "الشهر المقدر" مستنتج من نمط الأشهر السابقة ويستثني الأشهر المسجلة لديك هذا العام. عندما لا يعرض Yahoo تاريخ استحقاق مؤكداً خلال 90 يوماً يظهر التاريخ "—". المبلغ يبقى تقديراً فقط وليس إعلاناً رسمياً.',
    upcomingEstTwd: 'توزيع متوقع (TWD)',
    upcomingEstUsd: 'صافي متوقع بعد الضريبة (USD)',
    dataFromYahoo: 'مصدر البيانات: Yahoo Finance (مخزن محلياً)',
    disclaimerShort: 'للاسترشاد فقط، وليس نصيحة ضريبية أو قانونية.',
    usBadgeShort: '70%',
    nhiForecastTag: 'تقدير: هذا التوزيع قد يفعّل اقتطاع قسط NHI الإضافي',
    pendingActualTitle: 'توزيعات فعلية بانتظار التأكيد',
    pendingActualSubtitle: 'توزيعات حدث استحقاقها خلال 90 يوماً ولم تظهر بعد في السجلات؛ الضغط على "إضافة" ينشئ معاملة توزيع نقدي.',
    pendingActualDripHint: 'لإعادة استثمار التوزيعات (DRIP)، استخدم «+ إضافة سجل» من «السجل» — لا تضغط «إضافة إلى سجل المعاملات» هنا.',
    pendingActualEmpty: 'لا توجد حالياً توزيعات فعلية تحتاج للإضافة.',
    pendingActualLoading: 'جارٍ تحميل البيانات الفعلية...',
    pendingActualAddBtn: 'إضافة إلى سجل المعاملات',
    pendingActualAddCol: 'إضافة إلى سجل المعاملات',
    pendingActualDismissBtn: 'إخفاء',
    pendingActualToggleHide: 'إخفاء القائمة',
    pendingActualToggleShow: 'إظهار القائمة',
    pendingActualEstimatedDate: 'تاريخ دفع تقديري',
    pendingActualSourceMoneyDj: 'فعلي',
    pendingActualSourceYahoo: 'تكملة Yahoo',
    pendingActualPayDate: 'تاريخ الدفع',
    pendingActualPerShare: 'توزيع لكل سهم',
    pendingActualEstAmount: 'مبلغ تقديري',
    pendingActualAccount: 'حساب الإيداع',
    pendingActualNoteTemplate: 'استيراد تلقائي: لكل سهم {perShare}، الكمية {qty}',
  },
  funds: { 
    ...en.funds,
    title: 'إدارة الأموال',
    operations: 'العمليات',
    clearAll: 'مسح الأموال المفلترة',
    batchImport: 'استيراد مجمع',
    addRecord: '+ إضافة سجل',
    filter: 'تصفية',
    clearFilters: 'مسح جميع التصفيات',
    accountFilter: 'الحساب',
    typeFilter: 'النوع',
    dateFrom: 'من التاريخ',
    dateTo: 'إلى التاريخ',
    allAccounts: 'جميع الحسابات',
    allTypes: 'جميع الأنواع',
    deposit: 'إيداع',
    withdraw: 'سحب',
    transfer: 'تحويل',
    interest: 'فائدة',
    loanInterest: 'فائدة القرض',
    showRecords: 'عرض {count} سجل',
    totalRecords: 'الإجمالي {total}',
    last30Days: 'آخر 30 يوم',
    thisYear: 'هذا العام',
    confirmClearAll: 'هل تريد مسح سجلات الأموال المفلترة؟',
    confirmClearAllMessage: 'سيتم حذف {count} سجل(سجلات) إيداع وسحب وتحويل وفائدة ضمن التصفية الحالية.',
    confirmClear: 'حذف',
  },
  history: { 
    ...en.history,
    tabTransactions: 'سجل المعاملات',
    tabTimeline: 'الخط الزمني للحيازة',
    operations: 'العمليات',
    batchUpdateMarket: 'تحديث السوق المجمع',
    clearAll: 'مسح المعاملات المفلترة',
    batchImport: 'استيراد مجمع',
    addRecord: '+ إضافة سجل',
    filter: 'تصفية',
    accountFilter: 'تصفية حسب الحساب',
    tickerFilter: 'تصفية حسب الرمز',
    dateFrom: 'من التاريخ',
    dateTo: 'إلى التاريخ',
    includeCashFlow: 'تضمين سجلات التدفق النقدي',
    clearFilters: 'مسح جميع التصفيات',
    showingRecords: 'عرض {count} سجل',
    totalRecords: 'الإجمالي {total}: {transactionCount} معاملة{hasCashFlow}',
    last30Days: 'آخر 30 يوم',
    thisYear: 'هذا العام',
    noTransactions: 'لا توجد معاملات',
    noMatchingTransactions: 'لم يتم العثور على معاملات مطابقة',
    edit: 'تعديل',
    delete: 'حذف',
    includeCashFlowDesc: 'حدد لإظهار الإيداعات والسحوبات والتحويلات وما إلى ذلك لعرض تغييرات الرصيد',
    hiddenCashFlowRecords: '{count} سجل تدفق نقدي مخفي',
    cashFlowDeposit: 'إيداع',
    cashFlowWithdraw: 'سحب',
    cashFlowTransfer: 'تحويل خارج',
    cashFlowTransferIn: 'تحويل داخل',
  },
  stockTimeline: {
    ...en.stockTimeline,
    noTransactionsHint: 'لا توجد معاملات بعد. أضف معاملة أولاً.',
    searchPlaceholder: 'ابحث عن الرمز...',
    allMarkets: 'كل الأسواق',
    statusAll: 'الكل',
    statusHolding: 'محتفظ به',
    statusClosed: 'مغلق',
    sortByFirstBuy: 'ترتيب حسب أول شراء',
    sortByTicker: 'ترتيب حسب الرمز',
    sortByPLPercent: 'ترتيب حسب الربح/الخسارة %',
    countUnit: 'رموز',
    symbol: 'الرمز',
    plAndStatus: 'الربح/الخسارة / الحالة',
    holdingTitle: 'محتفظ به',
    closedTitle: 'مغلق',
    firstBuy: 'أول شراء',
    lastTrade: 'آخر صفقة',
    holdingDays: 'أيام الاحتفاظ',
    avgCost: 'متوسط التكلفة',
    currentPrice: 'السعر الحالي',
    holdingQty: 'الكمية',
    pl: 'الربح/الخسارة',
    fee: 'الرسوم',
    noMatches: 'لا توجد رموز مطابقة للفلاتر',
    legendBuy: 'شراء',
    legendSell: 'بيع',
    legendStockDividend: 'توزيع أسهم',
    legendCashDividend: 'توزيع نقدي',
    legendTransferIn: 'تحويل داخل',
    legendTransferOut: 'تحويل خارج',
    legendHolding: 'محتفظ به',
  },
  labels: { 
    ...en.labels, 
    date: 'التاريخ', 
    account: 'الحساب', 
    amount: 'المبلغ', 
    balance: 'الرصيد', 
    action: 'الإجراء',
    type: 'النوع',
    price: 'السعر',
    quantity: 'الكمية',
    currency: 'العملة', 
    fee: 'العمولة', 
    exchangeRate: 'سعر الصرف',
    totalCost: 'إجمالي التكلفة',
    category: 'الفئة',
    description: 'الرمز/الوصف',
    note: 'ملاحظة',
  },
  holdings: { 
    ...en.holdings, 
    portfolioHoldings: 'المراكز', 
    mergedDisplay: 'مدمج حسب الرمز',
    detailedDisplay: 'مفصل حسب الحساب',
    aiUpdatePrices: 'تحديث الأسعار وسعر الصرف (AI)', 
    aiSearching: 'جاري البحث (AI)...',
    market: 'السوق', 
    ticker: 'الرمز',
    quantity: 'الكمية',
    currentPrice: 'السعر الحالي',
    weight: 'الوزن',
    cost: 'إجمالي التكلفة',
    marketValue: 'القيمة السوقية',
    profitLoss: 'الربح/الخسارة',
    annualizedROI: 'العائد السنوي على الاستثمار',
    dailyChange: 'التغيير اليومي',
    avgPrice: 'متوسط السعر',
    noHoldings: 'لا توجد مراكز. يرجى إضافة معاملات.' 
  },
  accounts: { 
    ...en.accounts, 
    addAccount: 'إضافة حساب وسيط/بنكي', 
    accountName: 'اسم الحساب',
    accountNamePlaceholder: 'مثال: Fubon Securities, Firstrade',
    currency: 'العملة', 
    currencyTWD: 'دولار تايواني',
    currencyUSD: 'دولار أمريكي',
    currencyJPY: 'ين ياباني',
    currencyEUR: 'يورو',
    currencyGBP: 'جنيه إسترليني',
    currencyHKD: 'دولار هونغ كونغ',
    currencyKRW: 'وون كوري',
    currencyCNY: 'يوان صيني',
    currencyINR: 'روبية هندية',
    currencyCAD: 'دولار كندي',
    currencyAUD: 'دولار أسترالي', 
    currencySAR: 'ريال سعودي', 
    currencyBRL: 'ريال برازيلي',
    subBrokerage: 'وسيط خارجي',
    add: 'إضافة', 
    update: 'تحديث', 
    editAccount: 'تعديل الحساب',
    balance: 'الرصيد', 
    cancel: 'إلغاء',
    updateAccount: 'تحديث الحساب',
    confirmDelete: 'تأكيد حذف الحساب',
    confirmDeleteMessage: 'هل أنت متأكد من حذف "{name}"؟',
    deleteWarning: 'ملاحظة: لن يؤدي هذا إلى حذف سجلات المعاملات التاريخية لهذا الحساب، ولكن قد يسبب مشاكل عند التصفية.',
    deleteAccount: 'تأكيد الحذف',
    noAccounts: 'لا توجد حسابات بعد. يرجى إضافة حسابك الوسيط الأول أعلاه.',
    cashBalance: 'رصيد النقد',
    editAccountTitle: 'تعديل الحساب',
    accountKind: 'نوع الحساب',
    accountKindBrokerage: 'وساطة (استثمار)',
    accountKindLiability: 'خصوم (قرض)',
    debtKind: 'نوع القرض',
    debtKindPersonal: 'قرض شخصي',
    debtKindMortgage: 'رهن عقاري',
    debtKindSecurities: 'قرض أوراق مالية',
    annualInterestRate: 'المعدل السنوي (%)',
    creditLimit: 'حد الائتمان',
    linkedBrokerageAccount: 'حساب الوساطة المرتبط',
    debtBalance: 'أصل الدين المستحق',
    liabilityHint: 'السحب: سجّل فقط تحويل خصوم → وساطة.',
  },
  debt: {
    paymentAlertTitle: 'تذكير سداد القرض',
    paymentAlertBody: '«{name}» خلال {days} أيام ({date})، نحو {amount}. راجع الرصيد.',
    acknowledgePaid: 'وضع علامة مدفوع',
    remindLater: 'ذكّرني لاحقاً',
    spreadDangerTitle: 'تحذير: هامش سلبي',
    spreadWarningTitle: 'تحذير: هامش منخفض',
    spreadBody: '«{name}» عائد {ret}% مقابل تكلفة القرض {rate}% (أقل من هامش الأمان).',
    notAdvice: 'للمرجع فقط، ليس نصيحة استثمارية.',
    leverageNetNote: 'صافي الاستثمار قد يشمل اقتراضاً (~{amount}). فسّر العائد بعناية.',
  },
  stockSplit: {
    title: 'إدارة تقسيم الأسهم',
    hint: 'تبقى سجلات المعاملات بعدد الأسهم والسعر الأصليين وقت الإدخال؛ حدث التقسيم يطبّق فقط على حساب الحيازة والربح/الخسارة بدءاً من تاريخ النفاذ. إذا كانت المعاملات بعد تاريخ النفاذ مُدخلة بالفعل بعدد الأسهم بعد التقسيم فلا تُدخل الحدث مرة أخرى.',
    ticker: 'رمز السهم',
    tickerPlaceholder: 'مثال: 2330، AAPL',
    market: 'السوق',
    effectiveDate: 'تاريخ النفاذ',
    sharesFrom: 'عدد الأسهم قبل التقسيم',
    sharesTo: 'عدد الأسهم بعد التقسيم',
    splitRatio: 'نسبة التقسيم',
    note: 'ملاحظة',
    notePlaceholder: 'مثال: تقسيم أسهم يناير 2024',
    addButton: 'إضافة حدث تقسيم أسهم',
    listTitle: 'أحداث التقسيم المضبوطة',
    totalCount: 'الإجمالي {count}',
    emptyList: 'لا توجد أحداث تقسيم',
    tickerRequired: 'يرجى إدخال رمز السهم',
    dateRequired: 'يرجى اختيار تاريخ النفاذ',
    invalidRatio: 'عدد الأسهم قبل/بعد التقسيم يجب أن يكون أعداداً صحيحة موجبة',
    duplicateError: 'يوجد حدث تقسيم لنفس السهم والسوق وتاريخ النفاذ',
    addSuccess: 'تمت إضافة حدث التقسيم',
    deleteSuccess: 'تم حذف حدث التقسيم',
    deleteConfirmTitle: 'تأكيد حذف حدث التقسيم',
    deleteConfirmMessage: 'هل تريد حذف حدث التقسيم لـ {ticker} بتاريخ {date}؟',
  },
  rebalance: { 
    ...en.rebalance, 
    title: 'إعادة التوازن', 
    resetToCurrent: 'إعادة تعيين إلى الأوزان الحالية',
    totalAssets: 'إجمالي الأصول (بما في ذلك النقد)',
    enable: 'تفعيل',
    symbol: 'الرمز',
    currentPrice: 'السعر الحالي',
    currentValue: 'القيمة الحالية',
    currentWeight: 'الوزن الحالي',
    targetWeight: 'الوزن المستهدف',
    targetValue: 'القيمة المستهدفة',
    adjustAmount: 'مبلغ التعديل',
    suggestedAction: 'الإجراء المقترح',
    cash: 'النقد',
    totalEnabled: 'الإجمالي (العناصر المفعلة)',
    remainingFunds: 'الأموال المتبقية',
    notParticipating: 'غير مشارك',
    accounts: ' حسابات',
    description: 'الوصف:',
    description1: 'يتم دمج الأسهم التي تحمل نفس الاسم وعرضها تلقائياً. يتم تخصيص الأوزان المستهدفة بشكل متناسب لكل حساب بناءً على القيم الحالية.',
    description2: 'حدد عمود "تفعيل" لاختيار الأسهم/السندات التي تحتاج إلى إعادة التوازن. العناصر غير المحددة لن تشارك في حسابات إعادة التوازن.',
    description3: 'يمكن أيضاً تحديد النقد. إذا تم تحديده، يمكنك تعيين نسبة النقد المستهدفة يدوياً؛ إذا لم يتم تحديده، سيبقى النقد دون تغيير.',
    description4: 'يتم حفظ الأوزان المستهدفة تلقائياً. إذا لم يتم تعيين هدف النقد يدوياً، سيقوم النظام تلقائياً بحساب وتخصيص النسبة المتبقية للنقد؛ إذا تم تعيينه يدوياً، سيتم استخدام القيمة التي حددتها.',
    description5: 'إذا كانت نسبة "النقد" المستهدفة سالبة، فهذا يعني أن تخصيص الأسهم المستهدف يتجاوز 100%. يرجى تقليل بعض نسب الأسهم المستهدفة.',
    description6: 'انقر على "إعادة تعيين إلى الأوزان الحالية" لإعادة تعيين جميع القيم المستهدفة بسرعة إلى الحالة الحالية.',
    buy: 'شراء', 
    sell: 'بيع',
    accountLabel: '(الحساب)',
    sharesLabel: '(الأسهم)',
    totalLabel: 'الإجمالي (',
    accountCount: 'حسابات',
  },
  simulator: { 
    ...en.simulator, 
    title: 'محاكي التخصيص', 
    description: 'تسمح لك هذه الأداة بمقارنة العوائد المتوقعة لتخصيصات الأصول المختلفة. أدخل معدلات العائد السنوية منذ التأسيس لأسهم أو صناديق ETF مختلفة كافتراضات، وسيحسب النظام الأداء المتوقع لمحفظتك بناءً على نسب التخصيص الخاصة بك.',
    descriptionWarning: '⚠️ ملاحظة: الأداء السابق لا يضمن النتائج المستقبلية. هذا المحاكي للرجوع إليه فقط.',
    basicSettings: 'الإعدادات الأساسية',
    initialAmount: 'مبلغ الاستثمار الأولي',
    investmentYears: 'سنوات الاستثمار',
    regularInvestment: 'الاستثمار المنتظم (اختياري)',
    regularAmount: 'مبلغ الاستثمار المنتظم',
    frequency: 'تكرار الاستثمار',
    monthly: 'شهري',
    quarterly: 'ربع سنوي',
    yearly: 'سنوي',
    annualTotal: 'إجمالي الاستثمار السنوي',
    setToZero: 'اضبط على 0 لتعطيل الاستثمار المنتظم',
    importFromHoldings: 'استيراد من المراكز الموجودة',
    importButton: 'استيراد من المراكز الموجودة',
    manualAdd: 'إضافة أصل يدوياً',
    ticker: 'رمز السهم',
    tickerPlaceholder: 'مثال: 0050',
    market: 'السوق',
    marketTW: 'تايوان (TW)',
    marketUS: 'الولايات المتحدة (US)',
    marketUK: 'بريطانيا (UK)',
    marketJP: 'اليابان (JP)',
    marketCN: 'الصين (CN)',
    marketSZ: 'الصين شنتشن (SZ)',
    marketIN: 'الهند (IN)',
    marketCA: 'كندا (CA)',
    marketFR: 'فرنسا (FR)',
    marketHK: 'هونغ كونغ (HK)',
    marketKR: 'كوريا الجنوبية (KR)',
    marketDE: 'ألمانيا (DE)',
    marketAU: 'أستراليا (AU)',
    marketSA: 'السعودية (SA)',
    marketBR: 'البرازيل (BR)',
    annualReturn: 'العائد السنوي (%)',
    allocation: 'التخصيص (%)',
    add: 'إضافة',
    addRow: 'إضافة صف',
    action: 'الإجراء',
    delete: 'حذف',
    addAll: 'إضافة الكل',
    yearlyInvestment: 'الاستثمار السنوي',
    assetList: 'قائمة توزيع الأصول',
    autoBalance: 'موازنة تلقائية',
    clearAll: 'مسح الكل',
    allocationSum: 'إجمالي التخصيص:',
    totalInvested: 'إجمالي المبلغ المستثمر',
    finalValue: 'القيمة النهائية',
    totalReturn: 'إجمالي العائد',
    portfolioAnnualReturn: 'العائد السنوي للمحفظة',
    initial: 'الابتدائي',
    yearlyProjection: 'مخطط التوقع السنوي',
    yearlyReturnAnalysis: 'تحليل العائد السنوي',
    detailedYearlyProjection: 'توقع سنوي مفصل',
    year: 'السنة',
    assetValue: 'قيمة الأصل',
    yearlyReturn: 'العائد السنوي',
    cumulativeInvestment: 'الاستثمار التراكمي',
    yearlyReturnRate: 'معدل العائد السنوي',
    allocationWarning: '⚠️ يجب أن يكون مجموع التخصيص 100%، والقيمة الحالية',
    confirmClear: 'تأكيد المسح',
    confirmClearMessage: 'هل أنت متأكد من مسح جميع توزيعات الأصول؟ لا يمكن التراجع عن هذا الإجراء.',
    dataWarning: '⚠️ تحذير اكتمال البيانات:',
    dataWarningDesc: 'إذا كانت النتيجة أقل من المتوقع بوضوح، فقد يكون السبب نقص بيانات Yahoo Finance التاريخية. يُنصح بمراجعة المصادر الرسمية أو إدخال عائد سنوي أدق يدوياً.',
    autoQuery: '🔍 استعلام تلقائي',
    autoQueryTitle: 'استعلام تلقائي عن العائد السنوي منذ الطرح العام',
    querying: 'جارٍ الاستعلام',
    cagrExplanation: '📊 شرح حساب العائد السنوي:',
    cagrFormulaDesc: 'يستخدم النظام صيغة CAGR (معدل النمو السنوي المركب):',
    cagrFormula: 'CAGR = ((السعر الحالي / السعر الأولي) ^ (1 / السنوات)) - 1',
    cagrExample: 'يمثل هذا متوسط معدل العائد المركب سنوياً إذا تم الشراء عند الطرح العام الأولي والاحتفاظ به حتى الآن.',
    cagrExampleValue: 'مثال: يرتفع السهم من 100 إلى 200 على مدى 5 سنوات، العائد السنوي حوالي 14.87%',
    errorEnterTicker: 'يرجى إدخال رمز السهم',
    errorAllocationRange: 'يجب أن تكون نسبة التخصيص بين 0% و100%',
    errorAllocationSum: 'لا يمكن أن يتجاوز مجموع التخصيص 100%',
    errorNoHoldings: 'لا توجد حالياً بيانات حيازة للاستيراد',
    errorEnterTickerFirst: 'يرجى إدخال رمز السهم أولاً',
    errorCannotGetReturn: 'تعذّر الحصول على العائد السنوي لـ {ticker}، يرجى الإدخال يدوياً',
    errorQueryFailed: 'فشل استعلام العائد السنوي، يرجى الإدخال يدوياً',
    close: 'إغلاق',
    cancel: 'إلغاء',
    yearPrefix: 'السنة',
    yearSuffix: 'م',
    queryingReturn: 'جارٍ الاستعلام عن العائد السنوي لـ {ticker}...',
  },
  help: {
    dataManagement: 'إدارة البيانات',
    export: 'تصدير',
    exportDesc: 'تصدير المعاملات والحسابات والأسعار إلى JSON. يُنصح بالنسخ الاحتياطي الدوري.',
    downloadBackup: 'تحميل النسخة الاحتياطية (.json)',
    import: 'استيراد',
    importWarning: 'تحذير: استيراد نسخة احتياطية سيستبدل جميع البيانات الحالية.',
    uploadBackup: 'رفع ملف النسخ الاحتياطي',
    authorizedUsers: 'المستخدمون المصرح لهم',
    authorizedUsersDesc: 'البريد الذي يمكن تسجيل الدخول بدونه (مُخفى للخصوصية):',
    emailAccount: 'البريد',
    status: 'الحالة',
    systemAuthorized: 'مرخص من النظام',
    contact: 'ترخيص الشراء واتصال المسؤول',
    contactTitle: 'يعجبك النظام؟',
    contactDesc: 'غير عضو وترغب بحق استخدام دائم أو لديك اقتراحات/أخطاء؟ تواصل مع المطور. قد يتأخر الرد.',
    contactEmail: 'الاتصال بالمسؤول (بريد)',
    subscription: 'اشتراك العضوية (شراء داخل التطبيق)',
    subscriptionTitle: 'كن عضوًا / إدارة الاشتراك',
    subscriptionDesc: 'اشترك عبر App Store لفتح جميع الميزات. اعرض الخطط أو اشترِ أو استعد المشتريات هنا.',
    subscribeButton: 'فتح خطط الاشتراك',
    deleteAppAccount: 'حذف الحساب والبيانات',
    deleteAppAccountDesc: 'يمسح حالة تسجيل الدخول وجميع البيانات المحلية على هذا الجهاز نهائياً. لا يمكن التراجع. لإلغاء الاشتراك: الإعدادات → الاشتراكات.',
    confirmDeleteAppAccount: 'تأكيد حذف الحساب',
    confirmDeleteAppAccountMessage: 'سيتم حذف جميع البيانات المحلية لـ «{user}» نهائياً. المتابعة؟',
    documentation: 'التوثيق',
    copyAll: 'نسخ الكل',
    copied: 'تم النسخ!',
    print: 'طباعة',
    confirmImport: 'تحذير: تأكيد استبدال البيانات؟',
    confirmImportMessage: 'أنت على وشك استيراد {fileName}.',
    confirmImportWarning: 'سيتم حذف جميع المعاملات والإعدادات الحالية ولا يمكن التراجع.',
    confirmOverride: 'تأكيد الاستبدال',
    documentationContent: `# دليل مستخدم TradeView

> **الخصوصية** :
> بنية دون اتصال. **جميع البيانات مخزنة محلياً على جهازك** (تطبيق iOS/Android أو متصفح)، لا على خوادم. **لا جمع للبيانات الشخصية.**

## 1. مقدمة
TradeView أداة إدارة أصول لأسهم تايوان والولايات المتحدة تساعد المستثمرين على تتبع تغيرات الأصول وحساب العوائد وإدارة تدفقات الأموال.

## 2. البدء السريع
اتبع هذا الترتيب في الإعداد الأول (يطابق مسار قائمة الهامبرغر « الحسابات → الأموال → السجل → لوحة التحكم »):
1. **إنشاء حساب**: اذهب إلى « الحسابات » لإضافة حسابك المصرفي أو حساب الوساطة.
2. **استيراد الأموال**: اذهب إلى « الأموال »، اضغط « + إضافة سجل »، واختر النوع « إيداع » لتسجيل راتبك أو ودائعك.
3. **إضافة معاملة**: في « السجل »، اضغط « + إضافة سجل » في أعلى اليمين لإدخال شراء/بيع الأسهم.
4. **عرض التقارير**: ارجع إلى « لوحة التحكم » للملخص؛ **الأعضاء** يحصلون أيضاً على مخططات P/L التراكمي والتخصيص وأداء السوق وخريطة حرارة التوزيعات.

## 3. الميزات التفصيلية
الأقسام التالية بترتيب قائمة الهامبرغر (**الضيف** و**العضو** يختلفان قليلاً؛ راجع FAQ).

### لوحة التحكم
« لوحة التحكم » هي الصفحة الرئيسية الافتراضية مع بطاقات الملخص والمراكز. **الأعضاء** : مخططات P/L التراكمي والتخصيص وأداء السوق وخريطة حرارة التوزيعات. عند وجود دين في حساب خصوم، تظهر بطاقات **الائتمان والدين** (راجع Q&A أدناه).

**خريطة حرارة التوزيعات (الأعضاء)** : لـ **إعادة استثمار التوزيعات (DRIP)** المعلّق، اذهب إلى « السجل » و« + إضافة سجل »—لا تستخدم **إضافة إلى سجل المعاملات** على الخريطة (للتوزيعات النقدية فقط).

### السجل
سجّل الشراء والبيع والتوزيعات وتحويلات الأسهم. « + إضافة سجل » أعلى اليمين؛ « تحديث السوق المجمع » لتعديل عدة معاملات.

**أنواع المعاملات**
* **Buy/Sell** : شراء/بيع عام.
* **إعادة استثمار التوزيعات (DRIP)** : يزيد عدد الأسهم.
* **توزيع نقدي** : إيداع نقدي؛ يزيد الرصيد.
* **تحويل صادر** : نقل الأسهم من حساب وساطة.
* **تحويل وارد** : نقل الأسهم إلى حساب وساطة.

**تحويل الأسهم (وسيط A → وسيط B)**
**موصى به (خطوة واحدة)** : « + إضافة سجل » → النوع **تحويل صادر** → الحساب المصدر (A) → التاريخ والسوق والرمز والكمية → **حساب الوجهة (B)** → **تأكيد وحفظ**. التطبيق ينشئ **صادر ووارد معاً**؛ الوارد التلقائي **رسوم = 0**—أدخل الرسوم على **تحويل صادر**. السعر الافتراضي = متوسط التكلفة.

### الأموال
« + إضافة سجل » لتدفقات النقد :
* **إيداع** : تدفق خارجي (مثل الراتب).
* **سحب** : تدفق للخارج.
* **تحويل** : بين حسابات (بنك → وساطة).
* **فائدة** : فائدة على الودائع أو الوساطة.
* **فائدة القرض** : مصروف؛ على **حساب الوساطة** يقل النقد.

### الحسابات
أضف أو عدّل حسابات بنكية أو وساطة. **نوع الحساب** : **وساطة (استثمار)** أو **خصوم (دين)**؛ راجع Q&A أدناه.

### تقسيم الأسهم
« تقسيم الأسهم » يسجّل أحداث التقسيم. المعاملات تحتفظ بالكميات والأسعار المسجلة؛ التقسيم يعدّل المراكز وP/L من تاريخ السريان. لا تسجّل مرتين صفقات ما بعد التقسيم.

### إعادة التوازن (الأعضاء)
« إعادة التوازن » يحدد الأوزان المستهدفة؛ الرموز المتطابقة تُدمَج؛ حدّد **تفعيل** للمشاركة. الأوزان تُحفظ تلقائياً أو « إعادة تعيين إلى الأوزان الحالية ».

### المحاكي
« المحاكي » يقارن العوائد المتوقعة للتخصيصات. أدخل افتراضات العائد السنوي والأوزان؛ « 🔍 Auto Query » يجلب CAGR (يختلف عن **العائد السنوي (XIRR)** في « لوحة التحكم »). ⚠️ الأداء السابق لا يضمن النتائج المستقبلية. للمرجع فقط.

### الائتمان / حساب الخصوم (Q&A)

س: ماذا يعني « الرصيد » في حساب الخصوم؟
ج: **أصل الدين المستحق**، وليس نقداً متاحاً. رصيد صفر = مسدد.

س: كيف أنشئ حساب خصوم؟
ج: « الحسابات » → **نوع الحساب** **خصوم (دين)** → **الاسم** و**العملة** و**المعدل السنوي (%)** و**حد الائتمان** (اختياري) → **إضافة**. الرصيد الابتدائي **0**.

س: كيف أسجّل صرف البنك إلى الوساطة؟
ج: « الأموال » → **تحويل** → **خصوم → وساطة** → مبلغ الصرف. **قيد واحد فقط**.

س: كيف أسجّل سداد الأصل؟
ج: « الأموال » → **تحويل** → **وساطة → خصوم** → المبلغ = **الأصل فقط**.

س: أين أسجّل فائدة القرض؟
ج: **حساب الوساطة**. « الأموال » → **فائدة القرض** → وساطة. خصم « أصل + فائدة » : **قيدان** : ① تحويل (وساطة→خصوم) لل**أصل**؛ ② فائدة القرض على **الوساطة**.

س: متى يُعتبر القرض مسدداً؟
ج: عندما **يصل الرصيد إلى صفر**.

س: هل أحذف الحساب بعد السداد؟
ج: لا. احتفظ بالحساب والسجل. رصيد صفر يخفي قسم الدين.

س: كيف تظهر لوحة التحكم عند وجود دين؟
ج: **عمود « الرصيد / الدين » > 0** : بطاقات الائتمان والدين، **صافي الثروة**. **العمود = 0** : **إجمالي الأصول**.

## 4. الأسئلة الشائعة (FAQ)

س: كيف يتم حساب معدل العائد السنوي؟
ج: **العائد السنوي (XIRR)** في « لوحة التحكم » : عائد مرجح بالأموال—≠ CAGR السعري فقط. « المحاكي » : CAGR في الاستعلام التلقائي.

س: كيف يتم تحديد سعر الصرف؟
ج: USD/TWD عالمياً أعلى اليمين أو عند التحويل.

س: الفرق بين الضيف والعضو؟
ج: **الضيوف** : « لوحة التحكم »، « السجل »، « الأموال »، « الحسابات »، « تقسيم الأسهم »، « المحاكي » والأساسيات؛ بطاقات الملخص والمراكز. **الأعضاء** : « إعادة التوازن »، مخططات P/L التراكمي، التخصيص، أداء السوق، خريطة التوزيعات، تصحيح التاريخ بالذكاء الاصطناعي. اشترك من « النظام ».

س: ما هي مزايا العضوية؟
ج: إعادة التوازن، مخططات متقدمة، أداء السوق، خريطة التوزيعات، وتحليل البيانات التاريخية.

س: تخزين البيانات والخصوصية؟
ج: **البيانات محلية بالكامل.** **« تحميل النسخة الاحتياطية (.json) »** بانتظام.

س: لا يمكن تنزيل ملف النسخ الاحتياطي؟
ج: **iOS/Android** : مشاركة إلى الملفات أو iCloud. **الويب** في LINE : Safari أو Chrome.

س: لماذا لا يمكن تحديث أسعار الأسهم؟
ج: تحقق من السوق. « تحديث السوق المجمع » في « السجل ».

س: لماذا تختلف الأسعار عن « تحديث الأسعار وسعر الصرف (AI) »؟
ج: تأخير 3–5 دقائق. لا تستخدم للتداول؛ للإحصاء فقط. احتفظ باحتياطيات الطوارئ. شكراً.

س: كيف يُحسب « المستخدم / الحد / نسبة الاستخدام »؟
ج: عند **« الرصيد / الدين » > 0**. **المستخدم** = أصل الدين. **الحد** = حد الائتمان. **الاستخدام** = مستخدم ÷ حد × 100%.

س: كيف تُحسب « فائدة الشهر القادم المقدرة »؟
ج: الرصيد × المعدل السنوي(%) ÷ 100 ÷ 12. مثال: 2,000,000 @ 2.2% → ~**3,667**/شهر.

س: ما علاقة القرض بصافي الاستثمار وXIRR وصافي الثروة؟
ج: **سحب/سداد القرض** في **صافي الاستثمار** و**XIRR**؛ **فائدة القرض** لا. **صافي الثروة** = إجمالي الأصول − إجمالي الدين.

س: ما هو « تقدم ضريبة الدخل الأجنبي »؟
ج: **العملة الأساسية TWD** : **الإحصائيات التفصيلية** تقدّر الدخل الأجنبي (1M / 6.7M TWD). **للتخطيط الضريبي فقط**.

## 5. إخلاء المسؤولية المهم

**تحذير مخاطر الاستثمار** :
- ⚠️ الاستثمار ينطوي على مخاطر، الأداء السابق لا يضمن النتائج المستقبلية.
- يوفر هذا التطبيق وظائف إحصاءات وإدارة الأصول فقط ولا يوفر نصائح استثمارية.
- لا يحتوي هذا التطبيق على وظائف تداول الأوراق المالية ولا يمكنه تنفيذ عمليات شراء/بيع فعلية.
- يجب أن تتخذ جميع قرارات الاستثمار من قبل المستخدم وفقاً لتقديره الخاص، ويتحمل المستخدم جميع المخاطر المرتبطة بها.
- يجب على المستخدمين تقييم مخاطر الاستثمار بشكل مستقل واستشارة المستشارين الماليين المحترفين عند الحاجة.

**بيان عدم تقديم نصيحة استثمارية** :
- جميع المعلومات والتحليلات والرسوم البيانية والتوصيات من AI المقدمة من هذا التطبيق هي للإشارة فقط ولا تشكل أي نصيحة استثمارية.
- لا يضمن هذا التطبيق أي نتائج استثمارية أو معدلات عائد.
- يجب على المستخدمين اتخاذ قرارات استثمارية بناءً على ظروفهم الخاصة وهم مسؤولون عن جميع قرارات الاستثمار.

**دقة البيانات** :
- قد تختلف البيانات مثل أسعار الأسهم وأسعار الصرف المقدمة من هذا التطبيق عن أسعار السوق الفعلية بسبب تأخيرات الشبكة.
- لا ينبغي للمستخدمين استخدام بيانات هذا التطبيق كأساس مرجعي وحيد للمعاملات الفعلية.
- يُنصح بالرجوع إلى الأسعار في الوقت الفعلي المقدمة من شركات الأوراق المالية أو المؤسسات المالية.`,
    androidPublish: 'نشر متجر Android',
    androidPublishTitle: 'كيف تنشر على Google Play؟',
    androidPublishDesc: 'لف تطبيق الويب كتطبيق أندرويد بـ TWA:\n1. حساب مطور Google (25$).\n2. Bubblewrap CLI مع رابط الموقع.\n3. ارفع AAB إلى Play Console وقدم للمراجعة.',
  },
  transactionForm: {
    ...en.transactionForm,
    addTransaction: 'إضافة معاملة',
    editTransaction: 'تعديل المعاملة',
    date: 'التاريخ',
    account: 'الحساب',
    market: 'السوق',
    ticker: 'الرمز',
    tickerPlaceholder: 'مثال: 2330, AAPL',
    category: 'الفئة',
    price: 'السعر',
    quantity: 'الكمية (أسهم)',
    quantityFixed: 'الكمية (ثابت 1)',
    fees: 'العمولة/الضرائب',
    note: 'ملاحظة',
    cancel: 'إلغاء',
    saveTransaction: 'حفظ',
    updateTransaction: 'تحديث',
    confirmTitle: 'تأكيد المعاملة',
    confirmMessage: 'راجع المعلومات أدناه.',
    dateLabel: 'التاريخ:',
    accountLabel: 'الحساب:',
    marketLabel: 'السوق:',
    tickerLabel: 'الرمز:',
    typeLabel: 'النوع:',
    priceLabel: 'السعر:',
    quantityLabel: 'الكمية:',
    feesLabel: 'العمولة:',
    noteLabel: 'ملاحظة:',
    totalAmount: 'المبلغ الإجمالي:',
    shares: 'أسهم',
    cashDividendQuantityConfirm: '1 سجل',
    backToEdit: 'رجوع',
    confirmSave: 'تأكيد وحفظ',
    previewTitle: 'معاينة المبلغ:',
    calculationFormula: 'المعادلة:',
    calculationMethod: 'طريقة الحساب:',
    deductionShort: 'خصم',
    marketTW: 'تايوان (TW)',
    marketUS: 'الولايات المتحدة (US)',
    marketUK: 'بريطانيا (UK)',
    marketJP: 'اليابان (JP)',
    marketCN: 'الصين (CN)',
    marketSZ: 'الصين شنتشن (SZ)',
    marketIN: 'الهند (IN)',
    marketCA: 'كندا (CA)',
    marketFR: 'فرنسا (FR)',
    marketHK: 'هونغ كونغ (HK)',
    marketKR: 'كوريا الجنوبية (KR)',
    marketDE: 'ألمانيا (DE)',
    marketAU: 'أستراليا (AU)',
    marketSA: 'السعودية (SA)',
    marketBR: 'البرازيل (BR)',
    typeBuy: 'شراء',
    typeSell: 'بيع',
    typeDividend: 'إعادة استثمار التوزيعات (DRIP)',
    typeCashDividend: 'توزيع نقدي',
    typeTransferIn: 'تحويل وارد',
    typeTransferOut: 'تحويل صادر',
    transferInSectionTitle: 'معلومات تحويل الأصول الوارد',
    targetAccount: 'حساب التداول الهدف',
    targetAccountPlaceholder: 'يرجى اختيار الحساب الهدف...',
    placeholderPrice: 'السعر للسهم',
    placeholderQuantity: 'إجمالي التوزيع',
    errorNoAccount: 'أنشئ حساباً أولاً.',
    errorNoTargetAccount: 'يرجى اختيار حساب التداول الهدف.',
    errorSameTransferAccount: 'لا يمكن أن يكون حساب المصدر والهدف متطابقين.',
    errorInsufficientTransferOutQuantity: 'كمية التحويل الصادر تتجاوز الكمية المتاحة في الحيازة',
    availableTransferOutQuantity: 'المتاح: {quantity} {shares}',
    transferInConfirmHint: 'سيتم أيضاً إنشاء سجل تحويل وارد',
    feesShort: 'عمولة',
    formulaNote: ' (TW تقريب)',
  },
  fundForm: {
    ...en.fundForm,
    addFundRecord: 'إضافة سجل أموال',
    editFundRecord: 'تعديل سجل الأموال',
    date: 'التاريخ',
    type: 'النوع',
    account: 'الحساب',
    sourceAccount: 'الحساب المصدر',
    amount: 'المبلغ',
    targetAccount: 'الحساب المستهدف',
    selectAccount: 'اختر حساباً...',
    exchangeRate: 'سعر الصرف',
    exchangeRateUSD: 'سعر الصرف (TWD/USD)',
    exchangeRateJPY: 'سعر الصرف (TWD/JPY)',
    exchangeRateUsdTwd: 'سعر الصرف (USD/TWD)',
    exchangeRateUsdJpy: 'سعر الصرف (USD/JPY)',
    exchangeRatePair: 'سعر الصرف ({quote}/{base})',
    exchangeRateUsdBase: 'سعر الصرف (USD/{base})',
    exchangeRateInvalid: 'تعذّر تحويل السعر. تحقّق من عملة العرض وأسعار الصرف مقابل TWD.',
    crossCurrencyTransfer: 'تحويل بعملات مختلفة',
    usdConversion: 'تحويل USD',
    jpyConversion: 'تحويل JPY',
    sameCurrencyTransfer: 'نفس العملة (1.0)',
    fees: 'العمولة ({currency})',
    feesNote: 'عمولة التحويل',
    note: 'ملاحظة',
    cancel: 'إلغاء',
    updateRecord: 'تحديث',
    confirmExecute: 'تأكيد وحفظ',
    typeDeposit: 'إيداع',
    typeWithdraw: 'سحب',
    typeTransfer: 'تحويل',
    typeInterest: 'فائدة',
    confirmTitle: 'تأكيد سجل الأموال',
    confirmMessage: 'راجع المعلومات أدناه.',
    dateLabel: 'التاريخ:',
    typeLabel: 'النوع:',
    accountLabel: 'الحساب:',
    targetAccountLabel: 'الحساب المستهدف:',
    amountLabel: 'المبلغ:',
    exchangeRateLabel: 'سعر الصرف:',
    feesLabel: 'العمولة:',
    noteLabel: 'ملاحظة:',
    totalTWD: 'الإجمالي ({currency}):',
    backToEdit: 'رجوع',
    confirmSave: 'تأكيد',
    errorNoAccount: 'أنشئ حساباً أولاً.',
    recurringSectionTitle: 'الجداول وتنبيهات الدين',
    recurringRulesTitle: 'قواعد متكررة',
    recurringDayShort: 'اليوم {day} · {account} · {amount} {ccy}',
    recurringDisclaimer:
      'تُطبَّق الإيداعات عند فتح التطبيق. تُستكمل الأشهر الفائتة عند الفتح التالي. لا يوجد جدولة في الخلفية.',
    recurringDayOfMonth: 'يوم الشهر (1–31)',
    recurringStartMonth: 'شهر البداية (اختياري)',
    recurringStartMonthHint: 'اتركه فارغاً للبدء من شهر إنشاء القاعدة',
    recurringAddRule: 'إضافة قاعدة',
    recurringEditRule: 'تعديل القاعدة',
    recurringSaveRule: 'حفظ القاعدة',
    recurringDeleteRule: 'حذف القاعدة',
    recurringEnabled: 'مفعّل',
    recurringLastApplied: 'آخر تطبيق: {period}',
    recurringNoRules: 'لا توجد قواعد متكررة بعد',
    recurringDeleteConfirm: 'حذف هذه القاعدة؟ سجلات الإيداع الحالية تبقى.',
    recurringInvalidAmount: 'يرجى اختيار حساب وإدخال مبلغ صالح',
    recurringAmountTwdOptional: 'مبلغ TWD الفعلي (اختياري)',
    recurringAmountTwdHelp:
      'عملة أجنبية: نُقدّر التكلفة كالمبلغ × السعر + الرسوم. إذا اختلف مبلغ كشف الحساب، أدخل مبلغ الكشف لاستبدال التحويل. فارغ = الاعتماد على السعر فقط.',
    recurringNoteBadge: 'شهري',
    recurringKindDeposit: 'إيداع دوري (أصل نشط)',
    recurringKindDebtAlert: 'تذكير سداد القرض',
    recurringLeadDays: 'تذكير مسبق (أيام)',
    transferDebtDisbursementHint: 'سحب القرض: خصوم → وساطة؛ يُحسب في صافي الاستثمار.',
    transferDebtRepaymentHint: 'السداد: وساطة → خصوم.',
    debtAlertSettingsTitle: 'إعدادات تنبيهات الدين',
    minSafetySpread: 'هامش أمان الفارق (%)',
    minSafetySpreadHelp:
      'عند وجود **رصيد دين** على الخصوم، إذا كان عائد الوساطة المرتبطة − سعر القرض أقل من هذا الحد، يظهر تحذير في لوحة التحكم وهنا (استرشادي). يُخفى عند رصيد صفر. تذكيرات السداد: أضف قاعدة أعلاه.',
  },
  batchImportModal: {
    title: 'استيراد معاملات دفعة واحدة',
    selectAccount: '1. حدد حساب الاستيراد',
    selectAccountPlaceholder: '-- يرجى اختيار حساب --',
    noAccountsWarning: '⚠️ لا يمكن إجراء الاستيراد الدفعي',
    noAccountsMessage: 'لا توجد أي حسابات في النظام. انتقل أولاً إلى "الحسابات" لإنشاء حساب ثم عد للاستيراد.',
    tabPaste: 'لصق مباشر (Paste)',
    tabUpload: 'رفع ملف CSV (Upload)',
    pasteLabel: 'الصق بيانات Excel/الجدول هنا (الصيغة المدعومة: التاريخ | شراء/بيع/توزيع/تحويل | الرمز | السعر | الكمية | الرسوم | الإجمالي)',
    pasteFormat: '💡 فئة "التحويل": إذا كانت الكمية سالبة فهي تحويل صادر، وإذا كانت موجبة فهي تحويل وارد.',
    pasteTip: 'تلميح: اللصق المباشر من Excel بصيغة مفصولة بعلامات تبويب يعطي أفضل نتيجة.',
    pastePlaceholder:
      '2022/3/30\tشراء\tVT\t103.23\t1.00\t0.00\t103.23\n2025/2/11\tتحويل\tVT\t93.41\t-167.73\t0.00\t15667.99',
    parseButton: 'تحليل النص الملصق',
    uploadLabel: 'ملفات CSV المدعومة: Charles Schwab، Firstrade',
    uploadSupported: 'إذا تعذر تحليل CSV، جرّب تبويب اللصق النصي أولاً.',
    noFileSelected: 'لم يتم اختيار ملف',
    selectFile: 'اختر ملف',
    previewTitle: 'معاينة بيانات الاستيراد',
    previewSuccess: 'ناجح',
    previewSelected: 'محدد',
    previewFailed: 'غير ناجح',
    previewSelectTransactions: 'يرجى اختيار المعاملات المراد استيرادها',
    selectAll: 'تحديد الكل',
    deselectAll: 'إلغاء تحديد الكل',
    allSelected: 'تم تحديد الكل',
    selectedCount: 'تم اختيار {selected} / {total}',
    tableDate: 'التاريخ',
    tableAction: 'الإجراء',
    tableMarket: 'السوق',
    tableSymbol: 'الرمز',
    tableQty: 'الكمية',
    tablePrice: 'السعر',
    tableFees: 'الرسوم',
    tableAmount: 'المبلغ',
    cancel: 'إلغاء',
    confirmImport: 'تأكيد الاستيراد',
    confirmImportCount: '({count} سجل)',
    errorNoAccounts: 'لا توجد حسابات، لا يمكن الاستيراد',
    errorNoAccountSelected: 'يرجى اختيار حساب أولاً',
    errorNoData: 'لا يمكن الاستيراد: لا توجد بيانات. الصق النص ثم حلله، أو ارفع ملف CSV.',
    errorParseFirst: '⚠️ اضغط أولاً على "تحليل النص الملصق" وتأكد من ظهور البيانات في المعاينة قبل تأكيد الاستيراد.',
    errorNoTransactionsSelected: 'يرجى اختيار معاملة واحدة على الأقل للاستيراد',
    errorParseFailed: 'تعذّر تحليل البيانات. يوجد {count} سجل بصيغة غير صحيحة.',
    errorParseFailedCount: 'عدد السجلات الفاشلة: {count}',
    errorParseError: 'حدث خطأ أثناء التحليل: {error}. يرجى التحقق من تنسيق البيانات.',
  },
  historicalModal: {
    title: 'الأسعار التاريخية (Time Machine)',
    selectYearLabel: 'السنة',
    yearOption: '{year} سنة',
    noHistoryYears: 'لا توجد سنوات',
    fillYearEndButton: '🤖 إكمال نهاية {year}',
    aiSearching: 'جاري التحميل...',
    batchProgress: '⏳ {current}/{total} ({year})',
    batchFetchAll: '🚀 جلب كل السنوات',
    forceRefresh: 'إعادة الجلب بالقوة (استبدال)',
    yearEndDataTitle: 'بيانات نهاية {year}',
    exchangeRateLabel: 'السعر (USD/TWD):',
    colMarket: 'السوق',
    colTicker: 'الرمز',
    colClosePrice: 'الإغلاق ({year}/12/31)',
    noHoldingsThisYear: 'لا توجد مراكز لهذه السنة',
    pricePlaceholder: 'أدخل السعر',
    hintTitle: '💡 ملاحظات:',
    hintBullet1:
      'الزر الأول (🤖 إكمال نهاية {year}): السنة من القائمة؛ جلب 31 ديسمبر فقط؛ يملأ الأصفار أو الفراغات دون استبدال القيم الموجودة.',
    hintBullet2:
      '🚀 جلب الكل: 31/12 مع نهايات الأرباع Q1–Q3 (31/03، 30/06، 30/09) لرسوم بيانية فصلية حقيقية.',
    hintBullet3: 'فعّل «إعادة الجلب بالقوة» لاستبدال البيانات الحالية.',
    cancel: 'إلغاء',
    saveUpdateChart: 'حفظ وتحديث المخططات',
    alertAllComplete: 'تم. عُالجت {count} سنة (نهاية السنة + Q1–Q3).',
    alertNoUpdateNeeded:
      'جميع البيانات مكتملة.\nفعّل «إعادة الجلب بالقوة» للاستبدال.',
    alertFetchFailed:
      'تعذر جلب أسعار تاريخية لـ {count} رمز(ات). تحقق من الاتصال.\n\nالرموز: {tickers}',
    alertAiError: 'فشل التحديث. حاول لاحقاً.',
  },
  purchaseModal: {
    title: 'اختر خطة العضوية',
    subtitle: 'اختر الخطة المناسبة لفتح جميع الميزات المميزة',
    onlyAndroid: 'هذه الميزة متاحة فقط في تطبيق Android',
    loadProductsFailed: 'فشل تحميل المنتجات',
    loginFirst: 'يرجى تسجيل الدخول أولاً',
    purchaseFailed: 'فشل الشراء',
    monthlyTitle: 'اشتراك شهري',
    monthlyDesc: 'فوترة شهرية ويمكن الإلغاء في أي وقت',
    monthlyPrice: 'NT$ 60/شهرياً',
    yearlyTitle: 'اشتراك سنوي',
    yearlyDesc: 'فوترة سنوية وقيمة أفضل',
    yearlyPrice: 'NT$ 590/سنوياً',
    loading: 'جارٍ التحميل...',
    popular: 'الأكثر شيوعاً',
    processing: 'جارٍ المعالجة...',
    purchaseNow: 'اشترِ الآن',
    footer:
      'سيتم تفعيل العضوية تلقائياً بعد الشراء. يمكن إلغاء الاشتراك في أي وقت من Google Play Store.',
  },
  batchCashFlowModal: {
    title: 'استيراد تدفقات نقدية دفعة واحدة',
    guideTitle: 'تعليمات:',
    guideBody:
      'ألصق البيانات المنسوخة من Excel والتي تتضمن التاريخ وTWD وUSD والسعر والرسوم والإجمالي والحساب والفئة.',
    guideNoteFx:
      'ملاحظة: (1) TWD فقط: املأ TWD والإجمالي؛ اترك USD والسعر فارغين. (2) عبر الحدود TWD→USD: املأ السعر. (3) USD داخل الولايات المتحدة (ACH): لا صرف، السعر فارغ.',
    columnHeaderExample: 'التاريخ | TWD | USD | السعر | الرسوم | الإجمالي | الحساب | الفئة',
    pasteDemoRow1Account: 'بنك محلي',
    pastePlaceholderApprox: '(≈ {approx}؛ العملة الأساسية والأسعار)',
    parseFailed:
      'تعذر تحليل البيانات.\nالناجح: 0\nالفاشل: {count}\nتأكد أن التنسيق مفصول بعلامات تبويب (نسخ مباشر من Excel).',
    unmappedAccounts: 'يرجى ربط هذه الحسابات أولاً:\n{accounts}',
    mappingTitle: '1. مطابقة الحسابات',
    mappingDesc: 'اربط أسماء الحسابات في الملف بحسابات النظام لديك.',
    fileNameLabel: 'حساب الملف:',
    selectAccount: '-- اختر حساباً مطابقاً --',
    previewTitle: '2. معاينة البيانات',
    successLabel: 'ناجح',
    failedLabel: 'فاشل',
    failedUnit: 'صفوف',
    colDate: 'التاريخ',
    colType: 'الفئة',
    colAmount: 'المبلغ (USD/TWD)',
    colFee: 'الرسوم',
    colTwdCost: 'تكلفة TWD الفعلية',
    colFileAccount: 'حساب الملف',
    colMappedAccount: 'الحساب المطابق',
    unmapped: 'غير مطابق',
    cancel: 'إلغاء',
    parseData: 'تحليل البيانات',
    confirmImport: 'تأكيد الاستيراد',
  },
  appMessages: {
    alertTitleInfo: 'تنبيه',
    loginErrorTitle: 'خطأ تسجيل الدخول',
    loginSuccessTitle: 'تم تسجيل الدخول',
    loginFailedTitle: 'فشل تسجيل الدخول',
    updateSuccessTitle: 'تم التحديث',
    deleteSuccessTitle: 'تم الحذف',
    restoreSuccessTitle: 'تمت الاستعادة بنجاح',
    importFailedTitle: 'فشل الاستيراد',
    downloadErrorTitle: 'خطأ في التنزيل',
    genericErrorTitle: 'خطأ',
    enterEmail: 'يرجى إدخال البريد الإلكتروني',
    adminWelcome: 'مرحباً بعودتك أيها المسؤول!',
    adminPasswordWrong: 'كلمة مرور المسؤول غير صحيحة',
    guestLoginNotice:
      'تم تسجيل دخولك بوضع الضيف.\n\nللحصول على الوصول الكامل، اضغط «ترقية» لإرسال طلب بريد إلكتروني إلى المسؤول.',
    contactSubject: 'TradeView بلاغ خطأ / ملاحظات',
    contactBody:
      'مرحباً Admin،\n\nحسابي: {user}\n\nأود الإبلاغ عن المشكلة أو الاقتراح التالي:\n\n(يرجى وصف الخطأ أو خطوات إعادة الإنتاج أو اقتراح ميزة)\n\nشكراً لك.',
    updatePriceSuccess: 'تم تحديث {count} من الأسعار',
    updatePriceSuccessWithRate: 'تم تحديث {count} من الأسعار ومزامنة سعر الصرف إلى {rate}',
    autoUpdateFailed: 'فشل التحديث التلقائي',
    downloadFailed: 'فشل التنزيل. يرجى فتح هذه الصفحة في المتصفح.',
    shareTitle: 'ملف نسخ احتياطي TradeView',
    backupFailed: 'فشل النسخ الاحتياطي: {error}',
    restoreSuccess: 'تمت استعادة البيانات بنجاح!',
    importFailed: 'فشل الاستيراد: تنسيق الملف غير صالح.',
    txUpdated: 'تم تحديث المعاملة',
    marketUpdated: 'تم تحديث إعدادات السوق لـ {count} معاملة',
    txDeleted: 'تم حذف المعاملة',
    txCleared: '✅ تم مسح {count} معاملة بنجاح!',
    accountUpdated: 'تم تحديث الحساب "{name}"',
    accountDeleted: 'تم حذف الحساب "{name}"',
    cashFlowUpdated: 'تم تحديث سجل التدفق النقدي',
    cashFlowDeleted: 'تم حذف سجل التدفق النقدي',
    cashFlowCleared: '✅ تم مسح {count} سجل(سجلات) تدفق نقدي مفلتر!',
    historicalSaved: 'تم تحديث بيانات الأصول التاريخية. تم تصحيح التقارير باستخدام الأسعار الحقيقية.',
    loginPasswordPlaceholder: 'أدخل كلمة المرور',
    confirmClearTxTitle: 'تأكيد مسح المعاملات المفلترة؟',
    confirmClearTxMessage: 'سيتم حذف {count} معاملة ضمن التصفية الحالية. لا يمكن التراجع عن هذا الإجراء. يرجى التأكد من وجود نسخة احتياطية.',
    confirmClearAction: 'تأكيد المسح',
    deleteTxTitle: 'حذف المعاملة',
    deleteTxMessage: 'هل أنت متأكد من حذف هذه المعاملة؟',
    cashFlowDeleteTitle: 'حذف سجل التدفق النقدي',
    unknownAccount: 'حساب غير معروف',
    accountLabel: 'الحساب:',
    dateLabel: 'التاريخ:',
    typeLabel: 'النوع:',
    amountLabel: 'المبلغ:',
    cashFlowDeleteWarningTitle: '⚠️ تنبيه',
    cashFlowDeleteWarningBody:
      'يوجد {count} معاملات مرتبطة بهذا الحساب. قد يؤثر حذف هذا السجل على دقة رصيد الحساب.',
    cashFlowDeleteMessage: 'هل أنت متأكد من حذف سجل التدفق النقدي هذا؟ لا يمكن التراجع.',
    confirmDeleteAction: 'تأكيد الحذف',
  },
};
